name: CI/CD

on:
  push:
    branches: [ develop, testing ]
  pull_request:
    branches: [ develop, testing ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run tests
      run: pytest --cov=./ --cov-report=xml
    
    - name: Check SonarCloud Environment Variables
      run: |
        echo "GITHUB_TOKEN is set: ${{ secrets.GITHUB_TOKEN != '' }}"
        echo "SONAR_TOKEN is set: ${{ secrets.SONAR_TOKEN != '' }}"
        echo "SONAR_PROJECT_KEY is set: ${{ secrets.SONAR_PROJECT_KEY != '' }}"
        echo "SONAR_ORGANIZATION is set: ${{ secrets.SONAR_ORGANIZATION != '' }}"
    
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        args: >
          -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
          -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }}
